### ISSUE TITLE
Python import matches are sensitive to import order

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/semgrep#353] opened 2020-03-31 19:21 UTC
**Describe the bug**
An sgrep rule with multiple imports is sensitive to the order of imports. In general, import order should not matter.

**To Reproduce**
https://sgrep.live/vpl

**Expected behavior**
Matches are insensitive to import order

**Impact**
This behavior multiplies the number of rules that need to be written by `N!`

**Comment by ievans** [comment] 2020-03-31 19:23
Hi Nathan, sometimes the order of imports can matter though.

E.g.:
```
from a import c
from b import c
```
will have different behavior. What do you think about that case?

**Comment by nbrahms** [comment] 2020-03-31 19:25
Honestly, it seems like we're overoptimizing for a corner case instead of the 80% happy path. 

IMO we could solve this (much) later by detecting this kind of wacky pattern when it crops up in the rule.

**Comment by nbrahms** [comment] 2020-03-31 19:28
Another issue (which perhaps I can file separately), is that `pattern-inside` doesn't seem to work with `pattern-either`, which means I can't kind-of-solve this issue with https://sgrep.live/ZPp.

This means I have to write `N!` lint rules, not just `N!` patterns.

**Comment by nbrahms** [comment] 2020-03-31 19:32
Pointing out a suggestion if we want to have the user define when order matters and when it does not:

One could maybe write a rule like
```
(..., import a, import b, ...)
```

And, like other argument lists, we could ignore order here.

**Comment by aryx** [comment] 2020-03-31 19:42
Not a bug though, the order of statements matter at the toplevel unfortunately in Python.
In other languages the order truly does not matter.

**Comment by nbrahms** [comment] 2020-03-31 21:28
> Not a bug though, the order of statements matter at the toplevel unfortunately in Python.
> In other languages the order truly does not matter.

Fair point

**Comment by aryx** [comment] 2020-04-02 20:05
Maybe we could define the code equivalence:

import $A
import $B
<==>
import $B
import $A

so when one writes
import a
import b
...
foo()

the code equivalence would be applied on the first 2 lines of the pattern to also look for the other order.

**Comment by aryx** [comment] 2020-11-19 09:36
what about a AND with 2 patterns, one doing import a, the other import b, that way for sure they can be in any order in the file.

**Comment by aryx** [comment] 2020-11-19 10:21
I would close this issue if the AND solution is considered good enough.

**Closed** 2020-11-19 11:37 UTC
Labels: difficult, enhancement, lang:python, priority:medium
